apiVersion: batch/v1
kind: Job
metadata:
  name: kafka-topic-creator
  namespace: {{ .Values.namespace }}
spec:
  template:
    spec:
      restartPolicy: OnFailure
      containers:
      - name: create-topics
        image: {{ .Values.kafka.image }}
        command: ["/bin/sh", "-c"]
        args:
          - |
            echo "Aspetto Kafka..."
            until nc -z kafka.{{ .Values.namespace }}.svc.cluster.local {{ .Values.kafka.port }}; do sleep 2; done
            while read line; do
              kafka-topics.sh --create --if-not-exists $line --bootstrap-server kafka.{{ .Values.namespace }}.svc.cluster.local:{{ .Values.kafka.port }};
            done < /topics/topics.txt

        volumeMounts:
        - name: topics
          mountPath: /topics
      volumes:
      - name: topics
        configMap:
          name: kafka-topics
